/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
var skycons = new Skycons();
  // on Android, a nasty hack is needed: {"resizeClear": true}

  // you can add a canvas by it's ID...
  skycons.add("today", Skycons.PARTLY_CLOUDY_DAY);
  skycons.add("day1", Skycons.CLEAR_DAY);
  skycons.add("day2", Skycons.CLOUDY);
  skycons.add("day3", Skycons.RAIN);

  // start animation!
  skycons.play();
  
  // want to change the icon? no problem:
  skycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);
  
/*
Get value from Bootstrap dropdown menu
*/

$('.Taipei City').on('click', function(){
    alert($(this).text());
    var city="Taipei City";
       $.ajax('https://query.yahooapis.com/v1/public/yql', {
         method: 'GET',
         data: {
           q: 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="' + city + '")',
           format: 'json'
         },
         success: function (data) {
       var weatherInfo = data.query.results.channel;
             var cityMatch = 'It seems ' + weatherInfo.item.condition.text.toLowerCase()+' in '+ weatherInfo.location.city + ', ' + weatherInfo.location.country
             var noCity = 'Sorry, I found no city matching ' + city;

           if (data.query.count === 0 || data.query.results.channel.item.title === 'City not found') {
             responsiveVoice.speak(noCity);
             setSubtitle(noCity);
             return false;
           }
       console.log(weatherInfo);
       var temp = (weatherInfo.item.condition.temp-32)*5/9;
           $('.temperature').text(Math.round(temp));
           $('.date').text(weatherInfo.item.forecast.1.date);
           $('.how').text(weatherInfo.item.condition.text);
           
           var temp1h = (weatherInfo.item.forecast.3.high-32)*5/9;
           var temp1l = (weatherInfo.item.forecast.3.low-32)*5/9;
           $('.temp1').text(Math.round(temp1h)'-'Math.round(temp1l));
           $('.date1').text(weatherInfo.item.forecast.3.date);
           $('#day1').text(weatherInfo.item.forecast.3.text);
           
           var temp2h = (weatherInfo.item.forecast.4.high-32)*5/9;
           var temp2l = (weatherInfo.item.forecast.4.low-32)*5/9;
           $('.temp2').text(Math.round(temp2h)'-'Math.round(temp2l));
           $('.date2').text(weatherInfo.item.forecast.4.date);
           $('#day2').text(weatherInfo.item.forecast.4.text);
           
           var temp3h = (weatherInfo.item.forecast.5.high-32)*5/9;
           var temp3l = (weatherInfo.item.forecast.5.low-32)*5/9;
           $('.temp3').text(Math.round(temp3h)'-'Math.round(temp3l));
           $('.date3').text(weatherInfo.item.forecast.5.date);
           $('#day3').text(weatherInfo.item.forecast.5.text);
       console.log(cityMatch);
       console.log(nocity);
         }
       });
});
$('#dropdown li .New Taipei City').on('click', function(){
    alert($(this).text());
    var city="New Taipei City";
       $.ajax('https://query.yahooapis.com/v1/public/yql', {
         method: 'GET',
         data: {
           q: 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="' + city + '")',
           format: 'json'
         },
         success: function (data) {
       var weatherInfo = data.query.results.channel;
             var cityMatch = 'It seems ' + weatherInfo.item.condition.text.toLowerCase()+' in '+ weatherInfo.location.city + ', ' + weatherInfo.location.country
             var noCity = 'Sorry, I found no city matching ' + city;

           if (data.query.count === 0 || data.query.results.channel.item.title === 'City not found') {
             responsiveVoice.speak(noCity);
             setSubtitle(noCity);
             return false;
           }
       console.log(weatherInfo);
       var temp = (weatherInfo.item.condition.temp-32)*5/9;
           $('.temperature').text(Math.round(temp));
           $('.date').text(weatherInfo.item.forecast.1.date);
           $('.how').text(weatherInfo.item.condition.text);
           
           var temp1h = (weatherInfo.item.forecast.3.high-32)*5/9;
           var temp1l = (weatherInfo.item.forecast.3.low-32)*5/9;
           $('.temp1').text(Math.round(temp1h)'-'Math.round(temp1l));
           $('.date1').text(weatherInfo.item.forecast.3.date);
           $('#day1').text(weatherInfo.item.forecast.3.text);
           
           var temp2h = (weatherInfo.item.forecast.4.high-32)*5/9;
           var temp2l = (weatherInfo.item.forecast.4.low-32)*5/9;
           $('.temp2').text(Math.round(temp2h)'-'Math.round(temp2l));
           $('.date2').text(weatherInfo.item.forecast.4.date);
           $('#day2').text(weatherInfo.item.forecast.4.text);
           
           var temp3h = (weatherInfo.item.forecast.5.high-32)*5/9;
           var temp3l = (weatherInfo.item.forecast.5.low-32)*5/9;
           $('.temp3').text(Math.round(temp3h)'-'Math.round(temp3l));
           $('.date3').text(weatherInfo.item.forecast.5.date);
           $('#day3').text(weatherInfo.item.forecast.5.text);
       console.log(cityMatch);
       console.log(nocity);
         }
       });
});
$('#dropdown li .Taichungv City').on('click', function(){
    alert($(this).text());
    var city="Taichung City";
       $.ajax('https://query.yahooapis.com/v1/public/yql', {
         method: 'GET',
         data: {
           q: 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="' + city + '")',
           format: 'json'
         },
         success: function (data) {
       var weatherInfo = data.query.results.channel;
             var cityMatch = 'It seems ' + weatherInfo.item.condition.text.toLowerCase()+' in '+ weatherInfo.location.city + ', ' + weatherInfo.location.country
             var noCity = 'Sorry, I found no city matching ' + city;

           if (data.query.count === 0 || data.query.results.channel.item.title === 'City not found') {
             responsiveVoice.speak(noCity);
             setSubtitle(noCity);
             return false;
           }
       console.log(weatherInfo);
       var temp = (weatherInfo.item.condition.temp-32)*5/9;
           $('.temperature').text(Math.round(temp));
           $('.date').text(weatherInfo.item.forecast.1.date);
           $('.how').text(weatherInfo.item.condition.text);
           
           var temp1h = (weatherInfo.item.forecast.3.high-32)*5/9;
           var temp1l = (weatherInfo.item.forecast.3.low-32)*5/9;
           $('.temp1').text(Math.round(temp1h)'-'Math.round(temp1l));
           $('.date1').text(weatherInfo.item.forecast.3.date);
           $('#day1').text(weatherInfo.item.forecast.3.text);
           
           var temp2h = (weatherInfo.item.forecast.4.high-32)*5/9;
           var temp2l = (weatherInfo.item.forecast.4.low-32)*5/9;
           $('.temp2').text(Math.round(temp2h)'-'Math.round(temp2l));
           $('.date2').text(weatherInfo.item.forecast.4.date);
           $('#day2').text(weatherInfo.item.forecast.4.text);
           
           var temp3h = (weatherInfo.item.forecast.5.high-32)*5/9;
           var temp3l = (weatherInfo.item.forecast.5.low-32)*5/9;
           $('.temp3').text(Math.round(temp3h)'-'Math.round(temp3l));
           $('.date3').text(weatherInfo.item.forecast.5.date);
           $('#day3').text(weatherInfo.item.forecast.5.text);
       console.log(cityMatch);
       console.log(nocity);
         }
       });
});
$('#dropdown li .Tainan City').on('click', function(){
    alert($(this).text());
    var city="Tainan City";
       $.ajax('https://query.yahooapis.com/v1/public/yql', {
         method: 'GET',
         data: {
           q: 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="' + city + '")',
           format: 'json'
         },
         success: function (data) {
       var weatherInfo = data.query.results.channel;
             var cityMatch = 'It seems ' + weatherInfo.item.condition.text.toLowerCase()+' in '+ weatherInfo.location.city + ', ' + weatherInfo.location.country
             var noCity = 'Sorry, I found no city matching ' + city;

           if (data.query.count === 0 || data.query.results.channel.item.title === 'City not found') {
             responsiveVoice.speak(noCity);
             setSubtitle(noCity);
             return false;
           }
       console.log(weatherInfo);
       var temp = (weatherInfo.item.condition.temp-32)*5/9;
           $('.temperature').text(Math.round(temp));
           $('.date').text(weatherInfo.item.forecast.1.date);
           $('.how').text(weatherInfo.item.condition.text);
           
           var temp1h = (weatherInfo.item.forecast.3.high-32)*5/9;
           var temp1l = (weatherInfo.item.forecast.3.low-32)*5/9;
           $('.temp1').text(Math.round(temp1h)'-'Math.round(temp1l));
           $('.date1').text(weatherInfo.item.forecast.3.date);
           $('#day1').text(weatherInfo.item.forecast.3.text);
           
           var temp2h = (weatherInfo.item.forecast.4.high-32)*5/9;
           var temp2l = (weatherInfo.item.forecast.4.low-32)*5/9;
           $('.temp2').text(Math.round(temp2h)'-'Math.round(temp2l));
           $('.date2').text(weatherInfo.item.forecast.4.date);
           $('#day2').text(weatherInfo.item.forecast.4.text);
           
           var temp3h = (weatherInfo.item.forecast.5.high-32)*5/9;
           var temp3l = (weatherInfo.item.forecast.5.low-32)*5/9;
           $('.temp3').text(Math.round(temp3h)'-'Math.round(temp3l));
           $('.date3').text(weatherInfo.item.forecast.5.date);
           $('#day3').text(weatherInfo.item.forecast.5.text);
       console.log(cityMatch);
       console.log(nocity);
         }
       });
});
$('#dropdown li .Kaohsiung City').on('click', function(){
    alert($(this).text());
    var city="Kaohsiung City";
       $.ajax('https://query.yahooapis.com/v1/public/yql', {
         method: 'GET',
         data: {
           q: 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="' + city + '")',
           format: 'json'
         },
         success: function (data) {
       var weatherInfo = data.query.results.channel;
             var cityMatch = 'It seems ' + weatherInfo.item.condition.text.toLowerCase()+' in '+ weatherInfo.location.city + ', ' + weatherInfo.location.country
             var noCity = 'Sorry, I found no city matching ' + city;

           if (data.query.count === 0 || data.query.results.channel.item.title === 'City not found') {
             responsiveVoice.speak(noCity);
             setSubtitle(noCity);
             return false;
           }
       console.log(weatherInfo);
       var temp = (weatherInfo.item.condition.temp-32)*5/9;
           $('.temperature').text(Math.round(temp));
           $('.date').text(weatherInfo.item.forecast.1.date);
           $('.how').text(weatherInfo.item.condition.text);
           
           var temp1h = (weatherInfo.item.forecast.3.high-32)*5/9;
           var temp1l = (weatherInfo.item.forecast.3.low-32)*5/9;
           $('.temp1').text(Math.round(temp1h)'-'Math.round(temp1l));
           $('.date1').text(weatherInfo.item.forecast.3.date);
           $('#day1').text(weatherInfo.item.forecast.3.text);
           
           var temp2h = (weatherInfo.item.forecast.4.high-32)*5/9;
           var temp2l = (weatherInfo.item.forecast.4.low-32)*5/9;
           $('.temp2').text(Math.round(temp2h)'-'Math.round(temp2l));
           $('.date2').text(weatherInfo.item.forecast.4.date);
           $('#day2').text(weatherInfo.item.forecast.4.text);
           
           var temp3h = (weatherInfo.item.forecast.5.high-32)*5/9;
           var temp3l = (weatherInfo.item.forecast.5.low-32)*5/9;
           $('.temp3').text(Math.round(temp3h)'-'Math.round(temp3l));
           $('.date3').text(weatherInfo.item.forecast.5.date);
           $('#day3').text(weatherInfo.item.forecast.5.text);
       console.log(cityMatch);
       console.log(nocity);
         }
       });
});
$('#dropdown li .Keelung City').on('click', function(){
    alert($(this).text());
    var city="Keelung City";
       $.ajax('https://query.yahooapis.com/v1/public/yql', {
         method: 'GET',
         data: {
           q: 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="' + city + '")',
           format: 'json'
         },
         success: function (data) {
       var weatherInfo = data.query.results.channel;
             var cityMatch = 'It seems ' + weatherInfo.item.condition.text.toLowerCase()+' in '+ weatherInfo.location.city + ', ' + weatherInfo.location.country
             var noCity = 'Sorry, I found no city matching ' + city;

           if (data.query.count === 0 || data.query.results.channel.item.title === 'City not found') {
             responsiveVoice.speak(noCity);
             setSubtitle(noCity);
             return false;
           }
       console.log(weatherInfo);
       var temp = (weatherInfo.item.condition.temp-32)*5/9;
           $('.temperature').text(Math.round(temp));
           $('.date').text(weatherInfo.item.forecast.1.date);
           $('.how').text(weatherInfo.item.condition.text);
           
           var temp1h = (weatherInfo.item.forecast.3.high-32)*5/9;
           var temp1l = (weatherInfo.item.forecast.3.low-32)*5/9;
           $('.temp1').text(Math.round(temp1h)'-'Math.round(temp1l));
           $('.date1').text(weatherInfo.item.forecast.3.date);
           $('#day1').text(weatherInfo.item.forecast.3.text);
           
           var temp2h = (weatherInfo.item.forecast.4.high-32)*5/9;
           var temp2l = (weatherInfo.item.forecast.4.low-32)*5/9;
           $('.temp2').text(Math.round(temp2h)'-'Math.round(temp2l));
           $('.date2').text(weatherInfo.item.forecast.4.date);
           $('#day2').text(weatherInfo.item.forecast.4.text);
           
           var temp3h = (weatherInfo.item.forecast.5.high-32)*5/9;
           var temp3l = (weatherInfo.item.forecast.5.low-32)*5/9;
           $('.temp3').text(Math.round(temp3h)'-'Math.round(temp3l));
           $('.date3').text(weatherInfo.item.forecast.5.date);
           $('#day3').text(weatherInfo.item.forecast.5.text);
       console.log(cityMatch);
       console.log(nocity);
         }
       });
});
$('#dropdown li .Taoyuan City').on('click', function(){
    alert($(this).text());
    var city="Taoyuan City";
       $.ajax('https://query.yahooapis.com/v1/public/yql', {
         method: 'GET',
         data: {
           q: 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="' + city + '")',
           format: 'json'
         },
         success: function (data) {
       var weatherInfo = data.query.results.channel;
             var cityMatch = 'It seems ' + weatherInfo.item.condition.text.toLowerCase()+' in '+ weatherInfo.location.city + ', ' + weatherInfo.location.country
             var noCity = 'Sorry, I found no city matching ' + city;

           if (data.query.count === 0 || data.query.results.channel.item.title === 'City not found') {
             responsiveVoice.speak(noCity);
             setSubtitle(noCity);
             return false;
           }
       console.log(weatherInfo);
       var temp = (weatherInfo.item.condition.temp-32)*5/9;
           $('.temperature').text(Math.round(temp));
           $('.date').text(weatherInfo.item.forecast.1.date);
           $('.how').text(weatherInfo.item.condition.text);
           
           var temp1h = (weatherInfo.item.forecast.3.high-32)*5/9;
           var temp1l = (weatherInfo.item.forecast.3.low-32)*5/9;
           $('.temp1').text(Math.round(temp1h)'-'Math.round(temp1l));
           $('.date1').text(weatherInfo.item.forecast.3.date);
           $('#day1').text(weatherInfo.item.forecast.3.text);
           
           var temp2h = (weatherInfo.item.forecast.4.high-32)*5/9;
           var temp2l = (weatherInfo.item.forecast.4.low-32)*5/9;
           $('.temp2').text(Math.round(temp2h)'-'Math.round(temp2l));
           $('.date2').text(weatherInfo.item.forecast.4.date);
           $('#day2').text(weatherInfo.item.forecast.4.text);
           
           var temp3h = (weatherInfo.item.forecast.5.high-32)*5/9;
           var temp3l = (weatherInfo.item.forecast.5.low-32)*5/9;
           $('.temp3').text(Math.round(temp3h)'-'Math.round(temp3l));
           $('.date3').text(weatherInfo.item.forecast.5.date);
           $('#day3').text(weatherInfo.item.forecast.5.text);
       console.log(cityMatch);
       console.log(nocity);
         }
       });
});
$('#dropdown li .Hsinchu City').on('click', function(){
    alert($(this).text());
    var city="Hsinchuv City";
       $.ajax('https://query.yahooapis.com/v1/public/yql', {
         method: 'GET',
         data: {
           q: 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="' + city + '")',
           format: 'json'
         },
         success: function (data) {
       var weatherInfo = data.query.results.channel;
             var cityMatch = 'It seems ' + weatherInfo.item.condition.text.toLowerCase()+' in '+ weatherInfo.location.city + ', ' + weatherInfo.location.country
             var noCity = 'Sorry, I found no city matching ' + city;

           if (data.query.count === 0 || data.query.results.channel.item.title === 'City not found') {
             responsiveVoice.speak(noCity);
             setSubtitle(noCity);
             return false;
           }
       console.log(weatherInfo);
       var temp = (weatherInfo.item.condition.temp-32)*5/9;
           $('.temperature').text(Math.round(temp));
           $('.date').text(weatherInfo.item.forecast.1.date);
           $('.how').text(weatherInfo.item.condition.text);
           
           var temp1h = (weatherInfo.item.forecast.3.high-32)*5/9;
           var temp1l = (weatherInfo.item.forecast.3.low-32)*5/9;
           $('.temp1').text(Math.round(temp1h)'-'Math.round(temp1l));
           $('.date1').text(weatherInfo.item.forecast.3.date);
           $('#day1').text(weatherInfo.item.forecast.3.text);
           
           var temp2h = (weatherInfo.item.forecast.4.high-32)*5/9;
           var temp2l = (weatherInfo.item.forecast.4.low-32)*5/9;
           $('.temp2').text(Math.round(temp2h)'-'Math.round(temp2l));
           $('.date2').text(weatherInfo.item.forecast.4.date);
           $('#day2').text(weatherInfo.item.forecast.4.text);
           
           var temp3h = (weatherInfo.item.forecast.5.high-32)*5/9;
           var temp3l = (weatherInfo.item.forecast.5.low-32)*5/9;
           $('.temp3').text(Math.round(temp3h)'-'Math.round(temp3l));
           $('.date3').text(weatherInfo.item.forecast.5.date);
           $('#day3').text(weatherInfo.item.forecast.5.text);
       console.log(cityMatch);
       console.log(nocity);
         }
       });
});
$('#dropdown li .Hsinchu County').on('click', function(){
    alert($(this).text());
    var city="Hsinchu County";
       $.ajax('https://query.yahooapis.com/v1/public/yql', {
         method: 'GET',
         data: {
           q: 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="' + city + '")',
           format: 'json'
         },
         success: function (data) {
       var weatherInfo = data.query.results.channel;
             var cityMatch = 'It seems ' + weatherInfo.item.condition.text.toLowerCase()+' in '+ weatherInfo.location.city + ', ' + weatherInfo.location.country
             var noCity = 'Sorry, I found no city matching ' + city;

           if (data.query.count === 0 || data.query.results.channel.item.title === 'City not found') {
             responsiveVoice.speak(noCity);
             setSubtitle(noCity);
             return false;
           }
       console.log(weatherInfo);
       var temp = (weatherInfo.item.condition.temp-32)*5/9;
           $('.temperature').text(Math.round(temp));
           $('.date').text(weatherInfo.item.forecast.1.date);
           $('.how').text(weatherInfo.item.condition.text);
           
           var temp1h = (weatherInfo.item.forecast.3.high-32)*5/9;
           var temp1l = (weatherInfo.item.forecast.3.low-32)*5/9;
           $('.temp1').text(Math.round(temp1h)'-'Math.round(temp1l));
           $('.date1').text(weatherInfo.item.forecast.3.date);
           $('#day1').text(weatherInfo.item.forecast.3.text);
           
           var temp2h = (weatherInfo.item.forecast.4.high-32)*5/9;
           var temp2l = (weatherInfo.item.forecast.4.low-32)*5/9;
           $('.temp2').text(Math.round(temp2h)'-'Math.round(temp2l));
           $('.date2').text(weatherInfo.item.forecast.4.date);
           $('#day2').text(weatherInfo.item.forecast.4.text);
           
           var temp3h = (weatherInfo.item.forecast.5.high-32)*5/9;
           var temp3l = (weatherInfo.item.forecast.5.low-32)*5/9;
           $('.temp3').text(Math.round(temp3h)'-'Math.round(temp3l));
           $('.date3').text(weatherInfo.item.forecast.5.date);
           $('#day3').text(weatherInfo.item.forecast.5.text);
       console.log(cityMatch);
       console.log(nocity);
         }
       });
});
$('#dropdown li .Hsinchu County').on('click', function(){
    alert($(this).text());
    var city="Hsinchu County";
       $.ajax('https://query.yahooapis.com/v1/public/yql', {
         method: 'GET',
         data: {
           q: 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="' + city + '")',
           format: 'json'
         },
         success: function (data) {
       var weatherInfo = data.query.results.channel;
             var cityMatch = 'It seems ' + weatherInfo.item.condition.text.toLowerCase()+' in '+ weatherInfo.location.city + ', ' + weatherInfo.location.country
             var noCity = 'Sorry, I found no city matching ' + city;

           if (data.query.count === 0 || data.query.results.channel.item.title === 'City not found') {
             responsiveVoice.speak(noCity);
             setSubtitle(noCity);
             return false;
           }
       console.log(weatherInfo);
       var temp = (weatherInfo.item.condition.temp-32)*5/9;
           $('.temperature').text(Math.round(temp));
           $('.date').text(weatherInfo.item.forecast.1.date);
           $('.how').text(weatherInfo.item.condition.text);
           
           var temp1h = (weatherInfo.item.forecast.3.high-32)*5/9;
           var temp1l = (weatherInfo.item.forecast.3.low-32)*5/9;
           $('.temp1').text(Math.round(temp1h)'-'Math.round(temp1l));
           $('.date1').text(weatherInfo.item.forecast.3.date);
           $('#day1').text(weatherInfo.item.forecast.3.text);
           
           var temp2h = (weatherInfo.item.forecast.4.high-32)*5/9;
           var temp2l = (weatherInfo.item.forecast.4.low-32)*5/9;
           $('.temp2').text(Math.round(temp2h)'-'Math.round(temp2l));
           $('.date2').text(weatherInfo.item.forecast.4.date);
           $('#day2').text(weatherInfo.item.forecast.4.text);
           
           var temp3h = (weatherInfo.item.forecast.5.high-32)*5/9;
           var temp3l = (weatherInfo.item.forecast.5.low-32)*5/9;
           $('.temp3').text(Math.round(temp3h)'-'Math.round(temp3l));
           $('.date3').text(weatherInfo.item.forecast.5.date);
           $('#day3').text(weatherInfo.item.forecast.5.text);
       console.log(cityMatch);
       console.log(nocity);
         }
       });
});
$('#dropdown li .Changhua Country').on('click', function(){
    alert($(this).text());
    var city="Changhua Country";
       $.ajax('https://query.yahooapis.com/v1/public/yql', {
         method: 'GET',
         data: {
           q: 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="' + city + '")',
           format: 'json'
         },
         success: function (data) {
       var weatherInfo = data.query.results.channel;
             var cityMatch = 'It seems ' + weatherInfo.item.condition.text.toLowerCase()+' in '+ weatherInfo.location.city + ', ' + weatherInfo.location.country
             var noCity = 'Sorry, I found no city matching ' + city;

           if (data.query.count === 0 || data.query.results.channel.item.title === 'City not found') {
             responsiveVoice.speak(noCity);
             setSubtitle(noCity);
             return false;
           }
       console.log(weatherInfo);
       var temp = (weatherInfo.item.condition.temp-32)*5/9;
           $('.temperature').text(Math.round(temp));
           $('.date').text(weatherInfo.item.forecast.1.date);
           $('.how').text(weatherInfo.item.condition.text);
           
           var temp1h = (weatherInfo.item.forecast.3.high-32)*5/9;
           var temp1l = (weatherInfo.item.forecast.3.low-32)*5/9;
           $('.temp1').text(Math.round(temp1h)'-'Math.round(temp1l));
           $('.date1').text(weatherInfo.item.forecast.3.date);
           $('#day1').text(weatherInfo.item.forecast.3.text);
           
           var temp2h = (weatherInfo.item.forecast.4.high-32)*5/9;
           var temp2l = (weatherInfo.item.forecast.4.low-32)*5/9;
           $('.temp2').text(Math.round(temp2h)'-'Math.round(temp2l));
           $('.date2').text(weatherInfo.item.forecast.4.date);
           $('#day2').text(weatherInfo.item.forecast.4.text);
           
           var temp3h = (weatherInfo.item.forecast.5.high-32)*5/9;
           var temp3l = (weatherInfo.item.forecast.5.low-32)*5/9;
           $('.temp3').text(Math.round(temp3h)'-'Math.round(temp3l));
           $('.date3').text(weatherInfo.item.forecast.5.date);
           $('#day3').text(weatherInfo.item.forecast.5.text);
       console.log(cityMatch);
       console.log(nocity);
         }
       });
});
$('#dropdown li .Nantou Country').on('click', function(){
    alert($(this).text());
    var city="Nantou Country";
       $.ajax('https://query.yahooapis.com/v1/public/yql', {
         method: 'GET',
         data: {
           q: 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="' + city + '")',
           format: 'json'
         },
         success: function (data) {
       var weatherInfo = data.query.results.channel;
             var cityMatch = 'It seems ' + weatherInfo.item.condition.text.toLowerCase()+' in '+ weatherInfo.location.city + ', ' + weatherInfo.location.country
             var noCity = 'Sorry, I found no city matching ' + city;

           if (data.query.count === 0 || data.query.results.channel.item.title === 'City not found') {
             responsiveVoice.speak(noCity);
             setSubtitle(noCity);
             return false;
           }
       console.log(weatherInfo);
       var temp = (weatherInfo.item.condition.temp-32)*5/9;
           $('.temperature').text(Math.round(temp));
           $('.date').text(weatherInfo.item.forecast.1.date);
           $('.how').text(weatherInfo.item.condition.text);
           
           var temp1h = (weatherInfo.item.forecast.3.high-32)*5/9;
           var temp1l = (weatherInfo.item.forecast.3.low-32)*5/9;
           $('.temp1').text(Math.round(temp1h)'-'Math.round(temp1l));
           $('.date1').text(weatherInfo.item.forecast.3.date);
           $('#day1').text(weatherInfo.item.forecast.3.text);
           
           var temp2h = (weatherInfo.item.forecast.4.high-32)*5/9;
           var temp2l = (weatherInfo.item.forecast.4.low-32)*5/9;
           $('.temp2').text(Math.round(temp2h)'-'Math.round(temp2l));
           $('.date2').text(weatherInfo.item.forecast.4.date);
           $('#day2').text(weatherInfo.item.forecast.4.text);
           
           var temp3h = (weatherInfo.item.forecast.5.high-32)*5/9;
           var temp3l = (weatherInfo.item.forecast.5.low-32)*5/9;
           $('.temp3').text(Math.round(temp3h)'-'Math.round(temp3l));
           $('.date3').text(weatherInfo.item.forecast.5.date);
           $('#day3').text(weatherInfo.item.forecast.5.text);
       console.log(cityMatch);
       console.log(nocity);
         }
       });
});
$('#dropdown li .Yunlin Country').on('click', function(){
    alert($(this).text());
    var city="Yunlin Country";
       $.ajax('https://query.yahooapis.com/v1/public/yql', {
         method: 'GET',
         data: {
           q: 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="' + city + '")',
           format: 'json'
         },
         success: function (data) {
       var weatherInfo = data.query.results.channel;
             var cityMatch = 'It seems ' + weatherInfo.item.condition.text.toLowerCase()+' in '+ weatherInfo.location.city + ', ' + weatherInfo.location.country
             var noCity = 'Sorry, I found no city matching ' + city;

           if (data.query.count === 0 || data.query.results.channel.item.title === 'City not found') {
             responsiveVoice.speak(noCity);
             setSubtitle(noCity);
             return false;
           }
       console.log(weatherInfo);
       var temp = (weatherInfo.item.condition.temp-32)*5/9;
           $('.temperature').text(Math.round(temp));
           $('.date').text(weatherInfo.item.forecast.1.date);
           $('.how').text(weatherInfo.item.condition.text);
           
           var temp1h = (weatherInfo.item.forecast.3.high-32)*5/9;
           var temp1l = (weatherInfo.item.forecast.3.low-32)*5/9;
           $('.temp1').text(Math.round(temp1h)'-'Math.round(temp1l));
           $('.date1').text(weatherInfo.item.forecast.3.date);
           $('#day1').text(weatherInfo.item.forecast.3.text);
           
           var temp2h = (weatherInfo.item.forecast.4.high-32)*5/9;
           var temp2l = (weatherInfo.item.forecast.4.low-32)*5/9;
           $('.temp2').text(Math.round(temp2h)'-'Math.round(temp2l));
           $('.date2').text(weatherInfo.item.forecast.4.date);
           $('#day2').text(weatherInfo.item.forecast.4.text);
           
           var temp3h = (weatherInfo.item.forecast.5.high-32)*5/9;
           var temp3l = (weatherInfo.item.forecast.5.low-32)*5/9;
           $('.temp3').text(Math.round(temp3h)'-'Math.round(temp3l));
           $('.date3').text(weatherInfo.item.forecast.5.date);
           $('#day3').text(weatherInfo.item.forecast.5.text);
       console.log(cityMatch);
       console.log(nocity);
         }
       });
});
$('#dropdown li .Chiayi City').on('click', function(){
    alert($(this).text());
    var city="Chiayi City";
       $.ajax('https://query.yahooapis.com/v1/public/yql', {
         method: 'GET',
         data: {
           q: 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="' + city + '")',
           format: 'json'
         },
         success: function (data) {
       var weatherInfo = data.query.results.channel;
             var cityMatch = 'It seems ' + weatherInfo.item.condition.text.toLowerCase()+' in '+ weatherInfo.location.city + ', ' + weatherInfo.location.country
             var noCity = 'Sorry, I found no city matching ' + city;

           if (data.query.count === 0 || data.query.results.channel.item.title === 'City not found') {
             responsiveVoice.speak(noCity);
             setSubtitle(noCity);
             return false;
           }
       console.log(weatherInfo);
       var temp = (weatherInfo.item.condition.temp-32)*5/9;
           $('.temperature').text(Math.round(temp));
           $('.date').text(weatherInfo.item.forecast.1.date);
           $('.how').text(weatherInfo.item.condition.text);
           
           var temp1h = (weatherInfo.item.forecast.3.high-32)*5/9;
           var temp1l = (weatherInfo.item.forecast.3.low-32)*5/9;
           $('.temp1').text(Math.round(temp1h)'-'Math.round(temp1l));
           $('.date1').text(weatherInfo.item.forecast.3.date);
           $('#day1').text(weatherInfo.item.forecast.3.text);
           
           var temp2h = (weatherInfo.item.forecast.4.high-32)*5/9;
           var temp2l = (weatherInfo.item.forecast.4.low-32)*5/9;
           $('.temp2').text(Math.round(temp2h)'-'Math.round(temp2l));
           $('.date2').text(weatherInfo.item.forecast.4.date);
           $('#day2').text(weatherInfo.item.forecast.4.text);
           
           var temp3h = (weatherInfo.item.forecast.5.high-32)*5/9;
           var temp3l = (weatherInfo.item.forecast.5.low-32)*5/9;
           $('.temp3').text(Math.round(temp3h)'-'Math.round(temp3l));
           $('.date3').text(weatherInfo.item.forecast.5.date);
           $('#day3').text(weatherInfo.item.forecast.5.text);
       console.log(cityMatch);
       console.log(nocity);
         }
       });
});
$('#dropdown li .Pingtung Country').on('click', function(){
    alert($(this).text());
    var city="Pingtung Country";
       $.ajax('https://query.yahooapis.com/v1/public/yql', {
         method: 'GET',
         data: {
           q: 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="' + city + '")',
           format: 'json'
         },
         success: function (data) {
       var weatherInfo = data.query.results.channel;
             var cityMatch = 'It seems ' + weatherInfo.item.condition.text.toLowerCase()+' in '+ weatherInfo.location.city + ', ' + weatherInfo.location.country
             var noCity = 'Sorry, I found no city matching ' + city;

           if (data.query.count === 0 || data.query.results.channel.item.title === 'City not found') {
             responsiveVoice.speak(noCity);
             setSubtitle(noCity);
             return false;
           }
       console.log(weatherInfo);
       var temp = (weatherInfo.item.condition.temp-32)*5/9;
           $('.temperature').text(Math.round(temp));
           $('.date').text(weatherInfo.item.forecast.1.date);
           $('.how').text(weatherInfo.item.condition.text);
           
           var temp1h = (weatherInfo.item.forecast.3.high-32)*5/9;
           var temp1l = (weatherInfo.item.forecast.3.low-32)*5/9;
           $('.temp1').text(Math.round(temp1h)'-'Math.round(temp1l));
           $('.date1').text(weatherInfo.item.forecast.3.date);
           $('#day1').text(weatherInfo.item.forecast.3.text);
           
           var temp2h = (weatherInfo.item.forecast.4.high-32)*5/9;
           var temp2l = (weatherInfo.item.forecast.4.low-32)*5/9;
           $('.temp2').text(Math.round(temp2h)'-'Math.round(temp2l));
           $('.date2').text(weatherInfo.item.forecast.4.date);
           $('#day2').text(weatherInfo.item.forecast.4.text);
           
           var temp3h = (weatherInfo.item.forecast.5.high-32)*5/9;
           var temp3l = (weatherInfo.item.forecast.5.low-32)*5/9;
           $('.temp3').text(Math.round(temp3h)'-'Math.round(temp3l));
           $('.date3').text(weatherInfo.item.forecast.5.date);
           $('#day3').text(weatherInfo.item.forecast.5.text);
       console.log(cityMatch);
       console.log(nocity);
         }
       });
});
$('#dropdown li .Ilan Country').on('click', function(){
    alert($(this).text());
    var city="Ilan Country";
       $.ajax('https://query.yahooapis.com/v1/public/yql', {
         method: 'GET',
         data: {
           q: 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="' + city + '")',
           format: 'json'
         },
         success: function (data) {
       var weatherInfo = data.query.results.channel;
             var cityMatch = 'It seems ' + weatherInfo.item.condition.text.toLowerCase()+' in '+ weatherInfo.location.city + ', ' + weatherInfo.location.country
             var noCity = 'Sorry, I found no city matching ' + city;

           if (data.query.count === 0 || data.query.results.channel.item.title === 'City not found') {
             responsiveVoice.speak(noCity);
             setSubtitle(noCity);
             return false;
           }
       console.log(weatherInfo);
       var temp = (weatherInfo.item.condition.temp-32)*5/9;
           $('.temperature').text(Math.round(temp));
           $('.date').text(weatherInfo.item.forecast.1.date);
           $('.how').text(weatherInfo.item.condition.text);
           
           var temp1h = (weatherInfo.item.forecast.3.high-32)*5/9;
           var temp1l = (weatherInfo.item.forecast.3.low-32)*5/9;
           $('.temp1').text(Math.round(temp1h)'-'Math.round(temp1l));
           $('.date1').text(weatherInfo.item.forecast.3.date);
           $('#day1').text(weatherInfo.item.forecast.3.text);
           
           var temp2h = (weatherInfo.item.forecast.4.high-32)*5/9;
           var temp2l = (weatherInfo.item.forecast.4.low-32)*5/9;
           $('.temp2').text(Math.round(temp2h)'-'Math.round(temp2l));
           $('.date2').text(weatherInfo.item.forecast.4.date);
           $('#day2').text(weatherInfo.item.forecast.4.text);
           
           var temp3h = (weatherInfo.item.forecast.5.high-32)*5/9;
           var temp3l = (weatherInfo.item.forecast.5.low-32)*5/9;
           $('.temp3').text(Math.round(temp3h)'-'Math.round(temp3l));
           $('.date3').text(weatherInfo.item.forecast.5.date);
           $('#day3').text(weatherInfo.item.forecast.5.text);
       console.log(cityMatch);
       console.log(nocity);
         }
       });
});
$('#dropdown li .Hualien Country').on('click', function(){
    alert($(this).text());
    var city="Hualien Country";
       $.ajax('https://query.yahooapis.com/v1/public/yql', {
         method: 'GET',
         data: {
           q: 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="' + city + '")',
           format: 'json'
         },
         success: function (data) {
       var weatherInfo = data.query.results.channel;
             var cityMatch = 'It seems ' + weatherInfo.item.condition.text.toLowerCase()+' in '+ weatherInfo.location.city + ', ' + weatherInfo.location.country
             var noCity = 'Sorry, I found no city matching ' + city;

           if (data.query.count === 0 || data.query.results.channel.item.title === 'City not found') {
             responsiveVoice.speak(noCity);
             setSubtitle(noCity);
             return false;
           }
       console.log(weatherInfo);
       var temp = (weatherInfo.item.condition.temp-32)*5/9;
           $('.temperature').text(Math.round(temp));
           $('.date').text(weatherInfo.item.forecast.1.date);
           $('.how').text(weatherInfo.item.condition.text);
           
           var temp1h = (weatherInfo.item.forecast.3.high-32)*5/9;
           var temp1l = (weatherInfo.item.forecast.3.low-32)*5/9;
           $('.temp1').text(Math.round(temp1h)'-'Math.round(temp1l));
           $('.date1').text(weatherInfo.item.forecast.3.date);
           $('#day1').text(weatherInfo.item.forecast.3.text);
           
           var temp2h = (weatherInfo.item.forecast.4.high-32)*5/9;
           var temp2l = (weatherInfo.item.forecast.4.low-32)*5/9;
           $('.temp2').text(Math.round(temp2h)'-'Math.round(temp2l));
           $('.date2').text(weatherInfo.item.forecast.4.date);
           $('#day2').text(weatherInfo.item.forecast.4.text);
           
           var temp3h = (weatherInfo.item.forecast.5.high-32)*5/9;
           var temp3l = (weatherInfo.item.forecast.5.low-32)*5/9;
           $('.temp3').text(Math.round(temp3h)'-'Math.round(temp3l));
           $('.date3').text(weatherInfo.item.forecast.5.date);
           $('#day3').text(weatherInfo.item.forecast.5.text);
       console.log(cityMatch);
       console.log(nocity);
         }
       });
});
$('#dropdown li .Taitung Country').on('click', function(){
    alert($(this).text());
    var city="Taitung Country";
       $.ajax('https://query.yahooapis.com/v1/public/yql', {
         method: 'GET',
         data: {
           q: 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="' + city + '")',
           format: 'json'
         },
         success: function (data) {
       var weatherInfo = data.query.results.channel;
             var cityMatch = 'It seems ' + weatherInfo.item.condition.text.toLowerCase()+' in '+ weatherInfo.location.city + ', ' + weatherInfo.location.country
             var noCity = 'Sorry, I found no city matching ' + city;

           if (data.query.count === 0 || data.query.results.channel.item.title === 'City not found') {
             responsiveVoice.speak(noCity);
             setSubtitle(noCity);
             return false;
           }
       console.log(weatherInfo);
       var temp = (weatherInfo.item.condition.temp-32)*5/9;
           $('.temperature').text(Math.round(temp));
           $('.date').text(weatherInfo.item.forecast.1.date);
           $('.how').text(weatherInfo.item.condition.text);
           
           var temp1h = (weatherInfo.item.forecast.3.high-32)*5/9;
           var temp1l = (weatherInfo.item.forecast.3.low-32)*5/9;
           $('.temp1').text(Math.round(temp1h)'-'Math.round(temp1l));
           $('.date1').text(weatherInfo.item.forecast.3.date);
           $('#day1').text(weatherInfo.item.forecast.3.text);
           
           var temp2h = (weatherInfo.item.forecast.4.high-32)*5/9;
           var temp2l = (weatherInfo.item.forecast.4.low-32)*5/9;
           $('.temp2').text(Math.round(temp2h)'-'Math.round(temp2l));
           $('.date2').text(weatherInfo.item.forecast.4.date);
           $('#day2').text(weatherInfo.item.forecast.4.text);
           
           var temp3h = (weatherInfo.item.forecast.5.high-32)*5/9;
           var temp3l = (weatherInfo.item.forecast.5.low-32)*5/9;
           $('.temp3').text(Math.round(temp3h)'-'Math.round(temp3l));
           $('.date3').text(weatherInfo.item.forecast.5.date);
           $('#day3').text(weatherInfo.item.forecast.5.text);
       console.log(cityMatch);
       console.log(nocity);
         }
       });
});
$('#dropdown li .Penghu Country').on('click', function(){
    alert($(this).text());
    var city="Penghu Country";
       $.ajax('https://query.yahooapis.com/v1/public/yql', {
         method: 'GET',
         data: {
           q: 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="' + city + '")',
           format: 'json'
         },
         success: function (data) {
       var weatherInfo = data.query.results.channel;
             var cityMatch = 'It seems ' + weatherInfo.item.condition.text.toLowerCase()+' in '+ weatherInfo.location.city + ', ' + weatherInfo.location.country
             var noCity = 'Sorry, I found no city matching ' + city;

           if (data.query.count === 0 || data.query.results.channel.item.title === 'City not found') {
             responsiveVoice.speak(noCity);
             setSubtitle(noCity);
             return false;
           }
       console.log(weatherInfo);
       var temp = (weatherInfo.item.condition.temp-32)*5/9;
           $('.temperature').text(Math.round(temp));
           $('.date').text(weatherInfo.item.forecast.1.date);
           $('.how').text(weatherInfo.item.condition.text);
           
           var temp1h = (weatherInfo.item.forecast.3.high-32)*5/9;
           var temp1l = (weatherInfo.item.forecast.3.low-32)*5/9;
           $('.temp1').text(Math.round(temp1h)'-'Math.round(temp1l));
           $('.date1').text(weatherInfo.item.forecast.3.date);
           $('#day1').text(weatherInfo.item.forecast.3.text);
           
           var temp2h = (weatherInfo.item.forecast.4.high-32)*5/9;
           var temp2l = (weatherInfo.item.forecast.4.low-32)*5/9;
           $('.temp2').text(Math.round(temp2h)'-'Math.round(temp2l));
           $('.date2').text(weatherInfo.item.forecast.4.date);
           $('#day2').text(weatherInfo.item.forecast.4.text);
           
           var temp3h = (weatherInfo.item.forecast.5.high-32)*5/9;
           var temp3l = (weatherInfo.item.forecast.5.low-32)*5/9;
           $('.temp3').text(Math.round(temp3h)'-'Math.round(temp3l));
           $('.date3').text(weatherInfo.item.forecast.5.date);
           $('#day3').text(weatherInfo.item.forecast.5.text);
       console.log(cityMatch);
       console.log(nocity);
         }
       });
});
$('#dropdown li .Kinmen Country').on('click', function(){
    alert($(this).text());
    var city="Kinmen Country";
       $.ajax('https://query.yahooapis.com/v1/public/yql', {
         method: 'GET',
         data: {
           q: 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="' + city + '")',
           format: 'json'
         },
         success: function (data) {
       var weatherInfo = data.query.results.channel;
             var cityMatch = 'It seems ' + weatherInfo.item.condition.text.toLowerCase()+' in '+ weatherInfo.location.city + ', ' + weatherInfo.location.country
             var noCity = 'Sorry, I found no city matching ' + city;

           if (data.query.count === 0 || data.query.results.channel.item.title === 'City not found') {
             responsiveVoice.speak(noCity);
             setSubtitle(noCity);
             return false;
           }
       console.log(weatherInfo);
       var temp = (weatherInfo.item.condition.temp-32)*5/9;
           $('.temperature').text(Math.round(temp));
           $('.date').text(weatherInfo.item.forecast.1.date);
           $('.how').text(weatherInfo.item.condition.text);
           
           var temp1h = (weatherInfo.item.forecast.3.high-32)*5/9;
           var temp1l = (weatherInfo.item.forecast.3.low-32)*5/9;
           $('.temp1').text(Math.round(temp1h)'-'Math.round(temp1l));
           $('.date1').text(weatherInfo.item.forecast.3.date);
           $('#day1').text(weatherInfo.item.forecast.3.text);
           
           var temp2h = (weatherInfo.item.forecast.4.high-32)*5/9;
           var temp2l = (weatherInfo.item.forecast.4.low-32)*5/9;
           $('.temp2').text(Math.round(temp2h)'-'Math.round(temp2l));
           $('.date2').text(weatherInfo.item.forecast.4.date);
           $('#day2').text(weatherInfo.item.forecast.4.text);
           
           var temp3h = (weatherInfo.item.forecast.5.high-32)*5/9;
           var temp3l = (weatherInfo.item.forecast.5.low-32)*5/9;
           $('.temp3').text(Math.round(temp3h)'-'Math.round(temp3l));
           $('.date3').text(weatherInfo.item.forecast.5.date);
           $('#day3').text(weatherInfo.item.forecast.5.text);
       console.log(cityMatch);
       console.log(nocity);
         }
       });
});
$('#dropdown li .Lianjiang County').on('click', function(){
    alert($(this).text());
    var city="Lianjiang County";
       $.ajax('https://query.yahooapis.com/v1/public/yql', {
         method: 'GET',
         data: {
           q: 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="' + city + '")',
           format: 'json'
         },
         success: function (data) {
       var weatherInfo = data.query.results.channel;
             var cityMatch = 'It seems ' + weatherInfo.item.condition.text.toLowerCase()+' in '+ weatherInfo.location.city + ', ' + weatherInfo.location.country
             var noCity = 'Sorry, I found no city matching ' + city;

           if (data.query.count === 0 || data.query.results.channel.item.title === 'City not found') {
             responsiveVoice.speak(noCity);
             setSubtitle(noCity);
             return false;
           }
       console.log(weatherInfo);
       var temp = (weatherInfo.item.condition.temp-32)*5/9;
           $('.temperature').text(Math.round(temp));
           $('.date').text(weatherInfo.item.forecast.1.date);
           $('.how').text(weatherInfo.item.condition.text);
           
           var temp1h = (weatherInfo.item.forecast.3.high-32)*5/9;
           var temp1l = (weatherInfo.item.forecast.3.low-32)*5/9;
           $('.temp1').text(Math.round(temp1h)'-'Math.round(temp1l));
           $('.date1').text(weatherInfo.item.forecast.3.date);
           $('#day1').text(weatherInfo.item.forecast.3.text);
           
           var temp2h = (weatherInfo.item.forecast.4.high-32)*5/9;
           var temp2l = (weatherInfo.item.forecast.4.low-32)*5/9;
           $('.temp2').text(Math.round(temp2h)'-'Math.round(temp2l));
           $('.date2').text(weatherInfo.item.forecast.4.date);
           $('#day2').text(weatherInfo.item.forecast.4.text);
           
           var temp3h = (weatherInfo.item.forecast.5.high-32)*5/9;
           var temp3l = (weatherInfo.item.forecast.5.low-32)*5/9;
           $('.temp3').text(Math.round(temp3h)'-'Math.round(temp3l));
           $('.date3').text(weatherInfo.item.forecast.5.date);
           $('#day3').text(weatherInfo.item.forecast.5.text);
       console.log(cityMatch);
       console.log(nocity);
         }
       });
});


